# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - 87462-ecommerce-prd

on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_cb54b01828ac4f84b09f55df18ab954b }}
        password: ${{ secrets.AzureAppService_ContainerPassword_0cca38e62f554990b7a144e3df4c6a0c }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_cb54b01828ac4f84b09f55df18ab954b }}/ecommerce-prd:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: '87462-ecommerce-prd'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_bd69e1dbb70a43bfacabbb5aa6d80e18 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_cb54b01828ac4f84b09f55df18ab954b }}/ecommerce-prd:${{ github.sha }}'