name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: docker login
      run: docker login -u dijounas -p dckr_pat_JE6PlWdbTxneG-n8BomWrcAjE38
    - name: build image
      run: docker build -t dijounas/study .
    - name: push to docker
      run: docker push dijounas/study
