name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: docker login
      run: docker login -u kazuke -p dckr_pat_1CS-q8L-k4KjFa--dkvMzwqYtQs
    - name: build image
      run: docker build -t kazuke/ecommerce .
    - name: push to docker
      run: docker push kazuke/ecommerce
